dist: xenial
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.24.0
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
      - expect-dev # for unbuffer: brings color back into travis logs
jobs:
  include:
    - stage: system testing, deploy to dockerhub
      name: maintenance
      language: python
      python:
        - "3.6"
      before_install:
        - sudo bash ci/travis/system-testing/maintenance before_install
      install:
        - unbuffer bash ci/travis/system-testing/maintenance install
      before_script:
        - unbuffer bash ci/travis/system-testing/maintenance before_script
      script:
        - unbuffer bash ci/travis/system-testing/maintenance script
      after_success:
        - unbuffer bash ci/travis/system-testing/maintenance after_success
      after_failure:
        - unbuffer bash ci/travis/system-testing/maintenance after_failure
      deploy:
        - provider: script
          skip_cleanup: true
          script: unbuffer bash ci/travis/deploy/maintenance deploy
          on:
            branch: master
