services:
  mongodb:
    deploy:
      placement:
        constraints: []

  elasticsearch:
    deploy:
      placement:
        constraints: []

  graylog:
    deploy:
      placement:
        constraints: []

  vector:
    extra_hosts:
      # send any request to K8S_MONITORING_FQDN to host machine
      # host-gateway is a special "feature" that allows accessing ost from within container
      # https://docs.docker.com/reference/cli/dockerd#configure-host-gateway-ip
      - "${K8S_MONITORING_FQDN}:host-gateway"
    deploy:
      placement:
        constraints: []
