services:
  mongodb:
    deploy:
      placement:
        constraints: []

  elasticsearch:
    deploy:
      placement:
        constraints: []

  graylog:
    deploy:
      placement:
        constraints: []

  vector:
    extra_hosts:
      - "${K8S_MONITORING_FQDN}:host-gateway" # https://docs.docker.com/reference/cli/dockerd#configure-host-gateway-ip
    deploy:
      placement:
        constraints: []
