services:
  mongodb:
    deploy:
      placement:
        constraints: []

  elasticsearch:
    deploy:
      placement:
        constraints: []

  graylog:
    deploy:
      placement:
        constraints: []

  vector:
    extra_hosts:
      - "${K8S_MONITORING_FQDN}:${HOST_PRIVATE_IP}"
    deploy:
      placement:
        constraints: []
