apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmagent-network-policy
spec:
  selector: >-
    app.kubernetes.io/name == "vmagent"
    && app.kubernetes.io/part-of == "{{ .Release.Name }}"
  egress:
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
        ports:
          - 6443
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ index .Values "victoria-metrics-k8s-stack" "vmagent" "spec" "port" }}
