apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmsingle-network-policy
spec:
  selector: >-
    app.kubernetes.io/name == "vmsingle"
    && app.kubernetes.io/part-of == "{{ .Release.Name }}"
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ index .Values "victoria-metrics-k8s-stack" "vmsingle" "spec" "port" }}
