apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmsingle-network-policy
spec:
  selector: >-
    app.kubernetes.io/name in {"{{ .Values.vmsingle1.server.fullnameOverride }}", "{{ .Values.vmsingle2.server.fullnameOverride }}"}
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.vmSingleServerCommon.service.servicePort }}
