version: "3.7"
services:
  traefik:
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--accesslog=false"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entryPoints.metrics.address=:8082"
      - "--metrics.prometheus.entryPoint=metrics"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.constraints=!LabelRegex(`io.simcore.zone`, `*`)"
      - "--tracing=true"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
      - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge=true"
      - "--certificatesresolvers.lehttpchallenge.acme.httpchallenge.entrypoint=http"
      - "--certificatesresolvers.lehttpchallenge.acme.email=anderegg@itis.swiss"
      - "--certificatesresolvers.lehttpchallenge.acme.storage=/letsencrypt/acme.json"
      # uncomment the caserver when testing such that let's encrypt does not ban us
      # - '--certificatesresolvers.lehttpchallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
    volumes:
      - "letsencrypt_certs:/letsencrypt"
    deploy:
      labels:
        - traefik.http.routers.api.tls=true
        - traefik.http.routers.api.tls.certresolver=lehttpchallenge
  whoami:
    deploy:
      labels:
        - traefik.http.routers.whoami.rule=Host(`${MONITORING_DOMAIN}`) && PathPrefix(`/whoami`)
        - traefik.http.routers.whoami.tls=true
        - traefik.http.routers.whoami.tls.certresolver=lehttpchallenge
    networks:
      - public

volumes:
  letsencrypt_certs:
