# https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-datasources
apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-datasource
  labels:
    # special label to be picked up by the grafana sidecar
    {{ .Values.grafanaDatasourceLabel }}: {{ .Values.grafanaDatasourceLabelValue }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Values.vmdistributed.fullnameOverride | default .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  # https://docs.victoriametrics.com/victoriametrics/victoriametrics-datasource/
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        # this plugin needs to be installed in grafana beforehand
        type: {{ .Values.grafanaVictoriaMetricsDatasourceType }}
        access: proxy
        # https://docs.victoriametrics.com/helm/victoria-metrics-distributed/#how-to-query-data
        # vmauth CR creates a service named vmauth-<vmauth-name> in the same namespace
        url: http://vmauth-{{ .Values.vmdistributed.read.global.vmauth.name }}.{{ .Release.Namespace }}.svc.{{ .Values.vmdistributed.global.cluster.dnsDomain }}:{{ .Values.vmdistributed.common.vmauth.spec.port }}/select/0/prometheus/
        isDefault: true
        editable: true
        uid: {{ .Values.grafanaVictoriaMetricsDatasourceUid }}
