apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmagent-zone-network-policy
spec:
  selector: app == "vmagent-zone" && part-of == "{{ .Release.Name }}"
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.vmdistributed.common.vmagent.spec.port }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.vmdistributed.common.vmsingle.spec.port }}
