apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: vmagent-network-policy
spec:
  selector: app == "vmagent" && part-of == "{{ .Release.Name }}"
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.vmdistributed.common.vmagent.spec.port }}
  egress:
    - action: Allow
      protocol: TCP
      destination:
        nets:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
        ports:
          - 6443
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - {{ .Values.vmdistributed.common.vmauth.spec.port }}
          - {{ .Values.vmdistributed.common.vmsingle.spec.port }}
          - {{ .Values.vmdistributed.common.vmagent.spec.port }}
