global:
  scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL}s
  evaluation_interval: ${PROMETHEUS_SCRAPE_INTERVAL}s
  scrape_timeout: ${PROMETHEUS_SCRAPE_TIMEOUT}s

scrape_configs:
  - job_name: 'federate' # A job defines a series of targets and parameters describing how to scrape them.
    scrape_interval: ${PROMETHEUS_SCRAPE_INTERVAL} # Overwrite the global scrape interval for this job,
    scrape_timeout: ${PROMETHEUS_SCRAPE_TIMEOUT} # Overwrite the global scrape timeout for this job.
    honor_labels: true # Do not overwrite labels in scraped data.
    scheme: http
    metrics_path: '/federate' # Path to fetch the metrics from, '/federate' is for federation.

    params:
      'match[]': # The match[] parameter is used to select the metrics to retrieve. Logical OR is used between match[] parameters.
        - '{__name__=~"s4l_.*"}' # Regex to select all metrics that start with 's4l_'
        - '{__name__=~"osparc_.*"}' # Regex to select all metrics that start with 'osparc_'
        - '{__name__=~"simcore_.*"}' # Regex to select all metrics that start with 'simcore_'

    static_configs:
      - targets: ['prometheuscatchall:9090'] # The targets section is where you specify the host and port of the Prometheus instances to scrape.
