# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32080
        hostPort: 80
      - containerPort: 32081
        hostPort: 81
      - containerPort: 32443
        hostPort: 443
      - containerPort: 32443
        hostPort: 8443  ## handle traefik [interal] http --> https redirect
    labels:
      ops: "true"
      simcore: "true"

# https://archive-os-3-26.netlify.app/calico/3.26/getting-started/kubernetes/kind/
networking:
  disableDefaultCNI: true
  # must match with cidr in https://raw.githubusercontent.com/projectcalico/calico/v3.26.4/manifests/custom-resources.yaml
  podSubnet: 192.168.0.0/16
