name: Deployment-agent

on:
  push:
    paths:
      - "services/deployment-agent/**"
      - "!**.md"
  pull_request:
    paths:
      - "services/deployment-agent/**"
      - "!**.md"

env:
  # secrets can be set in settings/secrets on github
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  #no buildkit right now since the labels from docker-compsoe are not used (bug that will be fixed soon)
  # DOCKER_BUILDKIT: 1
  # COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  unit-test-deployment-agent:
    name: Unit-testing deployment-agent
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7]
        os: [ubuntu-18.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python }}
      - name: show versions
        run: ./ci/helpers/show_system_versions.bash
      - uses: actions/cache@v1
        name: getting cached data
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install deployment-agent
        run: ./ci/github/unit-testing/deployment-agent.bash install
      - name: test
        run: ./ci/github/unit-testing/deployment-agent.bash test
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests #optional

  system-test-deployment-agent:
    name: System-testing deployment-agent
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.6, 3.7]
        os: [ubuntu-18.04]
      fail-fast: false
    steps:
      - name: set PR default variables
        # only pushes have access to the docker credentials, use a default
        if: github.event_name == 'pull_request'
        run: |
          export TMP_DOCKER_REGISTRY=${GITHUB_REPOSITORY%/*}
          echo ::set-env name=DOCKER_REGISTRY::${TMP_DOCKER_REGISTRY,,}
      - uses: actions/checkout@v2
      - name: setup python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python }}
      - name: show versions
        run: ./ci/helpers/show_system_versions.bash
      - uses: actions/cache@v1
        name: getting cached data
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install deployment-agent
        run: ./ci/github/system-testing/deployment-agent.bash install
      - name: test
        run: ./ci/github/system-testing/deployment-agent.bash test
      - uses: codecov/codecov-action@v1
        with:
          flags: unittests #optional
      - name: set owner variable
        run: echo ::set-env name=OWNER::${GITHUB_REPOSITORY%/*}
      - name: deploy master
        if: github.ref == 'refs/heads/master'
        env:
          TAG_PREFIX: master-github
        run: |
          ./ci/deploy/deployment-agent.bash
